;;; valsi-projects-test.el --- Multiple-project workflow tests -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:
;; Exercise two identically named projects through the actual overview, hub,
;; chunked scanner and window navigation.  Pipe processes stand in for CLIs.

;;; Code:

(require 'ert)
(require 'valsi)
(require 'valsi-projects)
(require 'valsi-test-refresh)

(defmacro valsi-projects-test--with-projects (&rest body)
  "Run BODY with projects A and B, their files FA and FB, and isolated state."
  (declare (indent 0))
  `(let* ((base (make-temp-file "valsi-projects-" t))
          (a (file-name-as-directory (expand-file-name "one/app" base)))
          (b (file-name-as-directory (expand-file-name "two/app" base)))
          (fa (expand-file-name "PLAN.md" a))
          (fb (expand-file-name "PLAN.md" b))
          (before (buffer-list))
          (parameters (mapcar (lambda (key) (cons key (frame-parameter nil key)))
                              '(valsi-project-layouts valsi-projects-origin valsi-project-current)))
          (valsi-project-file nil)
          (valsi-project--loaded t)
          (valsi-project--load-error nil)
          (valsi-project--roots nil)
          (valsi-project--saved-roots nil)
          (valsi-app-live-refresh--projects (make-hash-table :test #'equal))
          (valsi-terminal-agent--instances (make-hash-table :test #'equal))
          (valsi-global-mode nil)
          (valsi-app-auto-sidebar nil)
          (valsi-app-auto-command-rail nil)
          (valsi-app-live-refresh-step-limit 2)
          (discoveries (make-hash-table :test #'equal)))
     (make-directory a t)
     (make-directory b t)
     (with-temp-file fa (insert "# First\n- [ ] T001 First task\n"))
     (with-temp-file fb (insert "# Second\n- [ ] T002 Second task\n"))
     (unwind-protect
         (save-window-excursion
           (cl-letf (((symbol-function 'project-current)
                      (lambda (&optional _prompt directory)
                        (let ((directory (or directory default-directory)))
                          (cond ((string-prefix-p a directory) (cons 'transient a))
                                ((string-prefix-p b directory) (cons 'transient b))))))
                     ((symbol-function 'valsi-app--project-candidates)
                      (lambda (root)
                        (puthash root (1+ (gethash root discoveries 0)) discoveries)
                        (list (expand-file-name "PLAN.md" root))))
                     ((symbol-function 'valsi-app-live-refresh--watch-directory) #'ignore))
             ,@body))
       (dolist (buffer (seq-difference (buffer-list) before))
         (when (buffer-live-p buffer)
           (when-let* ((process (get-buffer-process buffer))) (delete-process process))
           (with-current-buffer buffer (set-buffer-modified-p nil))
           (kill-buffer buffer)))
       (valsi-app-live-refresh-reset)
       (dolist (parameter parameters)
         (set-frame-parameter nil (car parameter) (cdr parameter)))
       (delete-directory base t))))

(defun valsi-projects-test--row (root)
  "Move to ROOT's heading in the current overview."
  (goto-char (point-min))
  (let ((match (text-property-search-forward 'valsi-row-id (concat "section:" root) #'equal)))
    (should match)
    (goto-char (prop-match-beginning match))))

(ert-deftest valsi-projects-identity-and-persistence ()
  "Equal basenames stay separate, symlink aliases merge, and roots persist."
  (valsi-projects-test--with-projects
    (let ((alias (expand-file-name "alias" base))
          (valsi-project-file (expand-file-name "state/projects.eld" base)))
      (make-symbolic-link a alias)
      (valsi-project-remember a)
      (valsi-project-remember b)
      (valsi-project-register alias)
      (should (equal (list a b) (valsi-project-roots)))
      (let ((ha (valsi-app--buffer a nil)) (hb (valsi-app--buffer b nil)))
        (should-not (eq ha hb))
        (should (equal a (buffer-local-value 'valsi-project-root ha)))
        (should (equal b (buffer-local-value 'valsi-project-root hb))))
      (should-not (equal (valsi-app--buffer-name a t) (valsi-app--buffer-name b t)))
      (should-not (equal (valsi-app--command-rail-buffer-name a) (valsi-app--command-rail-buffer-name b)))
      (let ((valsi-project--roots nil) (valsi-project--saved-roots nil)
            (valsi-project--loaded nil))
        (should (equal (list a b) (valsi-project-roots)))
        (valsi-project-forget a)
        (should (equal (list b) (valsi-project-roots))))
      (should (file-exists-p fa))
      (should (equal "# First\n- [ ] T001 First task\n"
                     (with-temp-buffer (insert-file-contents fa) (buffer-string)))))))

(ert-deftest valsi-projects-invalid-state-is-not-overwritten ()
  "Bad declarations stay intact, and unavailable saved roots remain visible."
  (valsi-projects-test--with-projects
    (let ((valsi-project-file (expand-file-name "projects.eld" base))
          (valsi-project--loaded nil))
      (with-temp-file valsi-project-file (insert "(:version 99 :roots ())"))
      (valsi-project-roots)
      (should valsi-project--load-error)
      (should-error (valsi-project-remember a) :type 'user-error)
      (should (equal "(:version 99 :roots ())"
                     (with-temp-buffer (insert-file-contents valsi-project-file) (buffer-string)))))
    (valsi-project-register a)
    (delete-directory a t)
    (valsi-projects)
    (should (string-match-p "Directory unavailable" (buffer-string)))
    (should-not valsi-projects--subscriptions)
    (should-error (valsi-project-switch a) :type 'user-error)))

(ert-deftest valsi-projects-shared-refresh-and-error-isolation ()
  "The overview shares hub snapshots and keeps another project usable on error."
  (valsi-projects-test--with-projects
    (valsi-project-register a)
    (valsi-project-register b)
    (valsi-projects)
    (should (= 0 (hash-table-count discoveries)))
    (let ((overview (current-buffer)) (hub (valsi-app--buffer a nil)))
      (valsi-test-refresh-drain a)
      (valsi-test-refresh-drain b)
      (should (= 1 (gethash a discoveries)))
      (should (= 1 (gethash b discoveries)))
      (should (eq (buffer-local-value 'valsi-app--entries hub)
                  (valsi-app-live-refresh--project-snapshot (valsi-app-live-refresh--project a))))
      (with-current-buffer overview
        (should (string-match-p "1 artifacts" (buffer-string)))
        (valsi-projects-test--row b)
        (valsi-view-toggle-section)
        (should-not (valsi-view-section-expanded-p b t))
        (cl-letf (((symbol-function 'valsi-app--project-candidates)
                   (lambda (root) (if (equal root a) (error "Backend offline") (list fb)))))
          (valsi-projects-refresh)
          (valsi-test-refresh-drain a)
          (valsi-test-refresh-drain b))
        (should (string-match-p "Backend offline" (buffer-string)))
        (should (equal b (valsi-projects--selected-root)))
        (should-not (valsi-view-section-expanded-p b t))
        (should-not (valsi-app-live-refresh--project-status (valsi-app-live-refresh--project b)))
        (valsi-projects-filter "two/app")
        (should-not (string-match-p (regexp-quote a) (buffer-string)))
        (should (string-match-p "two/app" (buffer-string))))
      (kill-buffer overview)
      (should (valsi-app-live-refresh--project-subscribers (valsi-app-live-refresh--project a)))
      (should-not (valsi-app-live-refresh--project-subscribers (valsi-app-live-refresh--project b))))))

(ert-deftest valsi-projects-resume-layout-unsaved-source-and-process ()
  "Switching and Projects preserve split windows, point, unsaved text and a CLI."
  (valsi-projects-test--with-projects
    (let* ((source (find-file-noselect fa))
           (terminal (generate-new-buffer " *valsi-multi-agent*"))
           (process (make-pipe-process :name "valsi-multi-agent" :buffer terminal :noquery t)))
      (with-current-buffer terminal (setq default-directory a valsi-project-root a))
      (switch-to-buffer source)
      (insert "Unsaved\n")
      (goto-char 4)
      (delete-other-windows)
      (set-window-buffer (split-window-below) terminal)
      (valsi-project-switch b)
      (should (equal b valsi-app--root))
      (should (= 1 (length (window-list))))
      (valsi-project-switch a)
      (should (eq source (current-buffer)))
      (should (= 4 (point)))
      (should (= 2 (length (window-list))))
      (should (get-buffer-window terminal))
      (should (process-live-p process))
      (should (buffer-modified-p source))
      (valsi-projects)
      (should (derived-mode-p 'valsi-projects-mode))
      (valsi-projects-test--row a)
      (call-interactively (key-binding (kbd "RET")))
      (should (eq source (current-buffer)))
      (should (= 2 (length (window-list))))
      (valsi-projects)
      (call-interactively (key-binding (kbd "q")))
      (should (eq source (current-buffer)))
      (should (= 4 (point)))
      (should (equal "# First\n- [ ] T001 First task\n"
                     (with-temp-buffer (insert-file-contents fa) (buffer-string))))
      ;; A dead selected source falls back to its hub, never an unrelated buffer.
      (valsi-project-switch b)
      (with-current-buffer source (set-buffer-modified-p nil))
      (kill-buffer source)
      (valsi-project-switch a)
      (should (derived-mode-p 'valsi-app-mode))
      (should (equal a valsi-app--root)))))

(ert-deftest valsi-projects-agent-lifecycle-and-stale-reports ()
  "Real process events update both views, preserve sentinels and reject stale reports."
  (valsi-projects-test--with-projects
    (let ((sentinel-calls 0) terminal-names)
      (cl-letf (((symbol-function 'valsi-terminal-agent--eat) #'ignore)
                ((symbol-function 'valsi-terminal-agent--ensure-program) (lambda (program _) program))
                ((symbol-function 'eat-make)
                 (lambda (name &rest _)
                   (push name terminal-names)
                   (let ((buffer (generate-new-buffer name)))
                     (make-pipe-process :name name :buffer buffer :noquery t
                                        :sentinel (lambda (&rest _) (cl-incf sentinel-calls)))
                     buffer))))
        (let* ((ia (valsi-terminal-agent--start a "primary" 'pi))
               (ib (valsi-terminal-agent--start b "primary" 'pi))
               (hub (valsi-app--buffer a nil)))
          (should-not (equal (car terminal-names) (cadr terminal-names)))
          (valsi-projects)
          (valsi-terminal-agent-report-status ia 'blocked "Choose an option")
          (should (string-match-p "needs input" (buffer-string)))
          (should (string-match-p "Choose an option" (buffer-string)))
          (with-current-buffer hub (should (string-match-p "needs input" (buffer-string))))
          (valsi-projects-test--row a)
          (should-error (valsi-projects-remove) :type 'user-error)
          (delete-process (get-buffer-process (valsi-terminal-agent-instance-buffer ia)))
          (should (> sentinel-calls 0))
          (should (equal "stopped" (valsi-terminal-agent-status-label ia)))
          (should (string-match-p "1 stopped" (buffer-string)))
          (should (valsi-terminal-agent--live-p ib))
          (should-error (valsi-terminal-agent-report-status ia 'done) :type 'user-error)
          (let ((replacement (valsi-terminal-agent--start a "primary" 'pi)))
            (should-error (valsi-terminal-agent-report-status ia 'working) :type 'user-error)
            (should (equal "running" (valsi-terminal-agent-status-label replacement)))))))))

(ert-deftest valsi-projects-navigation-keys-and-source-view-isolation ()
  "Every navigation layer exposes Projects, and same-named source views stay separate."
  (valsi-projects-test--with-projects
    (dolist (map (list valsi-app-mode-map valsi-browse-mode-map
                       valsi-outline-mode-map valsi-view-list-mode-map))
      (should (eq #'valsi-projects (lookup-key map (kbd "P"))))
      (should (eq #'valsi-project-switch (lookup-key map (kbd "w")))))
    (dolist (map (list valsi-artifact-mode-map valsi-terminal-agent-mode-map))
      (should (eq #'valsi-projects (lookup-key map (kbd "C-c n P"))))
      (should (eq #'valsi-project-switch (lookup-key map (kbd "C-c n w")))))
    (let ((sa (find-file-noselect fa)) (sb (find-file-noselect fb)) ta tb oa ob)
      (with-current-buffer sa
        (setq ta (valsi-view-tabulated "*Same table*" [("Name" 20 t)] '((1 ["First"]))))
        (set-buffer sa)
        (valsi-artifact-minor-mode 1)
        (valsi-outline)
        (setq oa (current-buffer)))
      (with-current-buffer sb
        (setq tb (valsi-view-tabulated "*Same table*" [("Name" 20 t)] '((1 ["Second"]))))
        (set-buffer sb)
        (valsi-artifact-minor-mode 1)
        (valsi-outline)
        (setq ob (current-buffer)))
      (should-not (eq ta tb))
      (should-not (eq oa ob))
      (should (eq sa (buffer-local-value 'valsi-view--source-buffer ta)))
      (should (eq sb (buffer-local-value 'valsi-outline--source ob))))))

(ert-deftest valsi-projects-edit-attention-stays-in-its-project ()
  "An unsaved edit updates only its project's shared snapshot and attention."
  (valsi-projects-test--with-projects
    (let ((source (find-file-noselect fa)))
      (valsi-project-register a)
      (valsi-project-register b)
      (valsi-projects)
      (valsi-test-refresh-drain a)
      (valsi-test-refresh-drain b)
      (let ((other (valsi-app-live-refresh--project-snapshot (valsi-app-live-refresh--project b))))
        (with-current-buffer source
          (goto-char (point-max))
          (insert "- [ ] T003 Unsaved task\n"))
        (valsi-test-refresh-drain a)
        (should (eq other (valsi-app-live-refresh--project-snapshot (valsi-app-live-refresh--project b))))
        (should (= 1 (gethash b discoveries)))
        (should (string-match-p "modified · PLAN.md" (buffer-string)))
        (goto-char (point-min))
        (search-forward "modified · PLAN.md")
        (should (equal a (valsi-projects--selected-root)))
        (call-interactively (key-binding (kbd "RET")))
        (should (eq source (current-buffer)))
        (should (buffer-modified-p))
        (should (string-match-p "Unsaved task" (buffer-string)))
        (should-not (with-temp-buffer (insert-file-contents fa) (search-forward "Unsaved task" nil t)))))))

(ert-deftest valsi-projects-add-remove-and-outside-entry ()
  "Entry outside a project, adding, filtering and removing form a keyboard workflow."
  (valsi-projects-test--with-projects
    (with-temp-buffer
      (setq default-directory base)
      (call-interactively #'valsi)
      (should (derived-mode-p 'valsi-projects-mode))
      (should (string-match-p "No working projects yet" (buffer-string)))
      (cl-letf (((symbol-function 'project-prompt-project-dir) (lambda (&rest _) a)))
        (call-interactively (key-binding (kbd "+"))))
      (should (equal (list a) valsi-project--saved-roots))
      (valsi-projects-test--row a)
      (call-interactively (key-binding (kbd "-")))
      (should-not (valsi-project-roots))
      (should-not valsi-projects--subscriptions)
      (should-not (valsi-app-live-refresh--project-timer (valsi-app-live-refresh--project a)))
      (should (file-exists-p fa)))))

(ert-deftest valsi-projects-concurrent-reviews-stay-associated ()
  "Reviewing one project's proposal cannot replace another pending review."
  (valsi-projects-test--with-projects
    (require 'valsi-plan-review)
    (let ((sa (find-file-noselect fa)) (sb (find-file-noselect fb)) ra rb)
      (with-current-buffer sa
        (valsi-plan-review-update "# First\n- [x] T001 First task\n")
        (setq ra (current-buffer)))
      (with-current-buffer sb
        (valsi-plan-review-update "# Second\n- [x] T002 Second task\n")
        (setq rb (current-buffer)))
      (should-not (eq ra rb))
      (should (eq sa (buffer-local-value 'valsi-plan-review--target ra)))
      (should (eq sb (buffer-local-value 'valsi-plan-review--target rb)))
      (should (equal a (buffer-local-value 'valsi-project-root ra)))
      (should (equal b (buffer-local-value 'valsi-project-root rb))))))

(ert-deftest valsi-projects-diagnostics-stay-associated-and-can-repeat ()
  "Diagnostic views retain source identity and can be regenerated read-only."
  (valsi-projects-test--with-projects
    (let ((sa (find-file-noselect fa)) (sb (find-file-noselect fb)) da db)
      (cl-letf (((symbol-function 'valsi-tree) (lambda () (valsi-plan-parse (buffer-string))))
                ((symbol-function 'valsi-plan--lint-issues) (lambda (_) '("Example diagnostic")))
                ((symbol-function 'valsi-plan--missing-file-findings) #'ignore))
        (with-current-buffer sa (valsi-plan-lint) (setq da (window-buffer)))
        (with-current-buffer sb (valsi-plan-lint) (setq db (window-buffer)))
        (should-not (eq da db))
        (should (eq sa (buffer-local-value 'valsi-view--source-buffer da)))
        (with-current-buffer da
          (should (equal a valsi-project-root))
          (should (eq #'valsi-projects (key-binding (kbd "P"))))
          (should (eq #'valsi-project-menu (key-binding (kbd "M-n")))))
        (with-current-buffer sa
          (valsi-plan-lint)
          (should (eq da (window-buffer))))))))

(ert-deftest valsi-projects-remote-declarations-do-not-connect ()
  "Rendering a remembered remote root does not canonicalize or scan it."
  (valsi-projects-test--with-projects
    (let ((valsi-project--saved-roots '("/ssh:offline:/work/app/"))
          (truename (symbol-function 'file-truename)))
      (cl-letf (((symbol-function 'file-truename)
                 (lambda (name &rest args)
                   (should-not (file-remote-p name))
                   (apply truename name args))))
        (valsi-projects)
        (should (string-match-p "Remote · open to refresh" (buffer-string)))
        (should-not valsi-projects--subscriptions)
        (should (= 0 (hash-table-count discoveries)))))))

(ert-deftest valsi-projects-resize-retains-selection-and-visible-identity ()
  "Resizing changes density while preserving project selection and folded paths."
  (valsi-projects-test--with-projects
    (valsi-project-register a)
    (valsi-project-register b)
    (valsi-projects)
    (valsi-test-refresh-drain a)
    (valsi-test-refresh-drain b)
    (valsi-projects-test--row b)
    (valsi-view-toggle-section)
    (cl-letf (((symbol-function 'window-body-width) (lambda (&rest _) 140)))
      (valsi-projects--resized (selected-frame))
      (should (eq 'wide valsi-projects--layout))
      (should (equal b (valsi-projects--selected-root)))
      (should (string-match-p "app  1 artifacts" (buffer-string))))
    (cl-letf (((symbol-function 'window-body-width) (lambda (&rest _) 80)))
      (valsi-projects--resized (selected-frame))
      (should (eq 'narrow valsi-projects--layout))
      (should (equal b (valsi-projects--selected-root)))
      (should (string-match-p (regexp-quote (directory-file-name b)) (buffer-string)))
      (should-not (valsi-view-section-expanded-p b t)))
    (kill-buffer (current-buffer))
    (should-not (memq #'valsi-projects--resized window-size-change-functions))))

(ert-deftest valsi-projects-navigation-skips-heading-metadata ()
  "Forward and backward navigation visit the same rows at every width."
  (valsi-projects-test--with-projects
    (valsi-project-register a)
    (valsi-project-register b)
    (valsi-projects)
    (valsi-test-refresh-drain a)
    (valsi-test-refresh-drain b)
    (dolist (width '(80 140))
      (cl-letf (((symbol-function 'window-body-width)
                 (lambda (&rest _) width)))
        (valsi-projects--render)
        (valsi-projects-test--row a)
        (let ((first (point)))
          (call-interactively (key-binding (kbd "n")))
          (should (equal b (valsi-projects--selected-root)))
          (call-interactively (key-binding (kbd "p")))
          (should (= first (point)))
          (call-interactively (key-binding (kbd "p")))
          (should (= first (point))))))))

(provide 'valsi-projects-test)
;;; valsi-projects-test.el ends here
